          
version: '3'

services:
    clte_practice_backend:
        build:
            context: ./backend/
            dockerfile: ./Dockerfile
        ports:
             - "8080:80"
    clte_practice_frontend:
        build:
            context: ./frontend/
            dockerfile: ./Dockerfile
        depends_on:
             - clte_practice_backend
        ports:
             - "80:1080"
